data:
  raw_path: data/raw/telco_churn.csv
  processed_path: data/processed/telco_churn_clean.csv
  target: Churn
split:
  test_size: 0.2
  random_state: 42
  stratify: true
model:
  type: logreg
  C: 1.0
  max_iter: 1000
  class_weight: balanced
